color:
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  brandStrength: 0.9369836007244885
  lightness: 0.8938701157458127
  saturation: 0.5511133389081806
  rhythmicContrast: 0.6092912792228162
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: BOSA
layout_spectrum: 0.5243725827895105
typography_spectrum: 0.44641207717359066
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0169a9d0-e4f0-481d-9862-c4017d8807ec.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0169a9d0-e4f0-481d-9862-c4017d8807ec.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/51f4158b-fbfc-43b5-9ac9-6acca8a424be.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/51f4158b-fbfc-43b5-9ac9-6acca8a424be.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
content_rating:
  adult: false
title: BOSA studio
description: студия архитектуры и дизайна
